accounts/urls.py
from django.urls import re_path, path
from .views import Login, Logout, CreateProfile, profileView, editProfileView, createAvatarView, deleteAvatarView, VerificationUser
from django.conf import settings
from django.conf.urls.static import static
import os
#app_name = os.path.dirname(__file__).rsplit('/', 1)[1]
from pathlib import PurePath
app_name = PurePath(os.path.dirname(__file__)).parts[-1]

#app_name = 'accounts'

urlpatterns = [
    path('login/', Login.as_view(), name='login'),
    path('logout/', Logout.as_view(), name='logout'),
    path('profile/', profileView.as_view(), name='profile'),
    path('editprofile/',  editProfileView.as_view(), name='editProfile'),
    path('createprofile/',  CreateProfile.as_view(), name='createProfile'),
    path('createavatar/<int:related_obj>/',  createAvatarView.as_view(), name='createAvatar'),
    path('deleteAvatar/<int:pk>/',  deleteAvatarView.as_view(), name='deleteAvatar'),
    path('verify/<str:email>/<str:activation_key>/', VerificationUser.as_view(), name='verify')
]

basket/urls.py
from django.urls import re_path, path
from .views import addInvoicePosition, basketDetailView, minusInvoicePositionCount, dellInvoicePosition, buy
from django.conf import settings
from django.conf.urls.static import static
import os

from pathlib import PurePath
app_name = PurePath(os.path.dirname(__file__)).parts[-1]


urlpatterns = [
    path('invoice/', basketDetailView.as_view(), name='basket_detail'),
    path('addtobasket/<int:pk>/', addInvoicePosition.as_view(), name='addinvoiceposition'),
    path('minustobasket/<int:pk>/', minusInvoicePositionCount.as_view(), name='minusInvoicePositionCount'),
    path('dellInvoicePosition/<int:pk>/', dellInvoicePosition.as_view(), name='dellInvoicePosition'),
    path('buy', buy.as_view(), name = 'buy')
]

gbShop/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.flatpages import views as flat
#import mainapp.views as mainapp

urlpatterns = []

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += [
    path('admin/', admin.site.urls),
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    # path('add/', include('django.contrib.flatpages.urls')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('basket/', include('basket.urls', namespace='basket')),
    path('add/about/', flat.flatpage, {'url': 'add/about/'}, name='about'),
    re_path(r'^', include('mainapp.urls', namespace='mainapp')),
]



#urlpatterns = [
#    path('admin/', admin.site.urls),
#    re_path(r'^$', mainapp.index_view),
#    re_path(r'^index', mainapp.index_view),
#    re_path(r'^products', mainapp.products_view),
#    re_path(r'^contact', mainapp.contact_view),
#]

mainapp/urls.py
from django.urls import re_path, path
from .views import indexView, contactListView, productListView, productDetailView, productCreateView, productEditView, productPictureCreateView, productPictureDeleteView
from django.conf import settings
from django.conf.urls.static import static
import os
#app_name = os.path.dirname(__file__).rsplit('/', 1)[1]
app_name = 'mainapp'

urlpatterns = [
    path('products/category/<int:pk>/', productListView.as_view(), name='products_in_catogory'),
    path('products/<int:pk>/', productDetailView.as_view(), name='product_detail'),
    path('products/', productListView.as_view(), name='products'),
    # path('search/', searchView.as_view(), name='search'),
    path('addnewproduct', productCreateView.as_view(), name='create_product'),
    path('addnewproduct/category/<int:cat_id>/',  productCreateView.as_view(), name='create_product'),
    path('editproduct/<int:pk>/', productEditView.as_view(), name='edit_product'),
    path('createprodpicture/<int:related_obj>/',  productPictureCreateView.as_view(), name='create_product_picture'),
    path('deleteprodpicture/<int:pk>/',  productPictureDeleteView.as_view(), name='delete_product_picture'),
    path('contacts', contactListView.as_view(), name='contacts'),
    re_path(r'^$', indexView.as_view(), name='index'),
    path(' ', indexView.as_view(), name='index'),
]

mainapp/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _

# Create your models here.
class Core(models.Model):
    """ Базовый класс моделей"""
    title = models.CharField(_('Название'), max_length=255, blank=True, null=True)
    description = models.TextField(_('Описание'), blank=True, null=True)
    sort = models.IntegerField(_('Сортировка'), default=0, blank=True, null=True)
    active = models.BooleanField(_('Активно'), default=False)

    class Meta:
        ordering = ['sort']

    def __str__(self):
        return f'{self.title}'

    @property
    def verbose_name(self):
        return self._meta.verbose_name

    @property
    def verbose_name_plural(self):
        return self._meta.verbose_name_plural


class ProductCategory(Core):
    """Категория товара"""
    class Meta:
        verbose_name = _('Продуктовая категория')
        verbose_name_plural = _('Продуктовые категории')


class ProductManufacturer(Core):
    """Производитель товара"""
    class Meta:
        verbose_name = _('Производитель')
        verbose_name_plural = _('Производители')


class Product(Core):
    """Продукт/товар"""
    class Meta:
        verbose_name = _('Продукт')
        verbose_name_plural = _('Продукты')

    category = models.ForeignKey(ProductCategory, null=True, on_delete=models.SET_NULL)
    manufacturer = models.ForeignKey(ProductManufacturer, null=True, on_delete=models.SET_NULL)


class PriceCurrency(Core):
    """Класс валюты"""
    class Meta:
        verbose_name = _('Валюта')
        verbose_name_plural = _('Валюты')


class ProductPrice(Core):
    """Цена товара"""
    price = models.DecimalField(_('Цена'), default=0, decimal_places=0, max_digits=20)
    currency = models.ForeignKey(PriceCurrency, null=True, on_delete=models.SET_NULL)
    prod = models.ForeignKey(Product, verbose_name=_('Цены'), related_name='prices', blank=True, null=True, on_delete=models.CASCADE)

    class Meta:
        verbose_name = _('Цена на продукт')
        verbose_name_plural = _('Цены на продукты')


class Picture(Core):
    """Картинки для объектов"""
    class Meta:
        verbose_name = _('Картинка')
        verbose_name_plural = _('Картинки')

    image=models.ImageField(upload_to='images')
    related_obj=models.ForeignKey(Core, verbose_name=_('pictures'), blank=True, null=True, related_name='pictures', on_delete=models.CASCADE)


class Contact(Core):
    """Контакты"""

    class Meta:
        verbose_name = _('Контакт')
        verbose_name_plural = _('Контакты')

    phone = models.CharField(_('Телефон'), max_length=14)
    email = models.EmailField(_('Email'), max_length=64, null=True, blank=True)
    address = models.CharField(_('Адрес'), max_length=255)

mainapp/views.py
from django.shortcuts import render_to_response
from django.contrib.auth.mixins import UserPassesTestMixin, LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from .models import Product, Picture, ProductCategory, ProductManufacturer, ProductPrice, Contact
from django.views.generic import ListView, DetailView, CreateView, DeleteView, UpdateView, View
from django.utils.translation import ugettext_lazy as _


class indexView(ListView):
    """класс для представления index_view"""
    template_name = 'mainapp/index.html'
    model = Product

    def get_context_data(self, **kwargs):
        response = super().get_context_data(**kwargs)
        # response.update({'main_menu': main_menu})
        return response



class productDetailView(DetailView):
    """класс для представления product_detail_view"""
    model = Product
    template_name = 'mainapp/includes/inc-product-detail-view.html'

    def get_context_data(self, **kwargs):
        response = super().get_context_data(**kwargs)
        response['categories']= ProductCategory.objects.all()
        obj = response.get('object', None)
        obj_id = getattr(obj, 'id', 0)
        cat_id = getattr(obj, 'category', 0)

        product_list = Product.objects.exclude(id=obj_id).filter(category=cat_id).order_by('sort')

        response.update({'object_list': product_list })
        return response

class productCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):

    fields = '__all__'
    model = Product
    success_message = _('Продукт успешно добавлен')

    # def get_form_kwargs(self):
    #     form_kwargs = super().get_form_kwargs()
    #     form_kwargs['initial'] = {}
    #     form_kwargs['initial']['category'] = self.kwargs.get['cat_id']
    #     return form_kwargs

    def get_success_url(self):
        return reverse_lazy('mainapp:product_detail',args=(self.object.id or 0,))

class productEditView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    """docstring for AddView"""
    fields = '__all__'
    model = Product
    success_message = _('Данные продукта успешно изменены')

    def get_success_url(self):
        return reverse_lazy('mainapp:product_detail',args=(self.object.id or 0,))


class productPictureCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    """docstring for createAvatarView"""
    fields = ('image', 'title', 'active')
    model = Picture
    success_message = _('Изображение товара успешно добавлено')

    def form_valid(self, form):
        form.instance.related_obj_id = self.kwargs.get('related_obj')
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('mainapp:product_detail',args=(self.object.related_obj.id or 0,))

    def get_context_data(self, **kwargs):
        response = super().get_context_data(**kwargs)
        response['related_obj']= self.kwargs.get('related_obj')
        return response


class productPictureDeleteView(LoginRequiredMixin, SuccessMessageMixin, DeleteView):
    """docstring for DelView"""
    model = Picture
    success_message = _('Изображение товара было удалено')

    def get_success_url(self):
        return reverse_lazy('mainapp:product_detail',args=(self.object.related_obj.id or 0,))

#def index_view(request):
#    context = {'main_menu': main_menu, 'products': Product.objects.all()}
#    return render_to_response('mainapp/index.html', context)

#def products_view(request):
#    context = {'main_menu': main_menu, 'products': Product.objects.all()}
#    return render_to_response('mainapp/products-page.html', context)

class contactListView(ListView):
    template_name = 'mainapp/contact.html'
    model = Contact

    def get_context_data(self, **kwargs):
        response = super().get_context_data(**kwargs)
        #response.update({'main_menu': main_menu})
        return response

#def contact_view(request):
#    context = {'main_menu': main_menu, 'contacts': Contact.objects.all()}
#    return render_to_response('mainapp/contact.html', context)


class productListView(ListView):
    """класс для представления products_view"""
    # template_name = 'mainapp/product_detail.html'
    model = Product
    paginate_by = 3

    def get_context_data(self, **kwargs):
        response = super().get_context_data(**kwargs)
        response['categories']= ProductCategory.objects.all()
        return response

    def get_queryset(self):
        response = super().get_queryset()
        if hasattr(self, 'filter'):
            response = response.filter(**self.filter)
        # if 'search' in self.request.GET:
        #     search = self.request.GET.get('search', '')
        #     if search: # выдаю ВСЕ варианты поиска в категории ИЛИ в имени товара ИЛИ в его описании, оператор "|", склеивающий три запроса вместе
        #         response = (response.filter(**{'category__title__icontains': search}) |
        #                     response.filter(**{'title__icontains': search}) |    # icontains НЕ работает для sqllite
        #                     response.filter(**{'title__contains': search.capitalize() }) |
        #                     response.filter(**{'description__icontains': search}))
        return response

    def get(self, request, *args, **kwargs):
        pk = kwargs.pop('pk', None)
        if pk:
            self.filter = {'category': pk}
        return super().get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        search= self.request.POST.get('search')
        if search: # глупо, но я передаю полученный запрос по каналу GET в контроллер вида allView
            self.filter = {'title__contains': search}
        return super().get(request, *args, **kwargs)

mainapp/templates/mainapp/includes/_inc-header.html
{% load static i18n %}
<div class="header">
    <a class="logo" href="{% url 'mainapp:index_view' %}"></a>
    <ul class="menu">
        {% for object in main_menu %}
        <li>
            <a href="{{object.get_url}}" {% if active == object.title %}class="active-menu" {% endif %}>{{object.title}}</a>
        </li>
        {% endfor %}

        {% if user.is_authenticated %}
        <li>
            <a href="{% url 'accounts:logout' %}">{% trans 'Logout' %}</a>
        </li>
        {% else %}
        <li>
            <a href="{% url 'accounts:login' %}">{% trans 'Login' %}</a>
        </li>
        {% endif %}
        <li><a href="{% url 'mainapp:products' %}"><img src="{% static 'img/search.svg' %}" alt="search"></a></li>
        <li>{% if user.is_authenticated %}<a href="#"><img src="{% static 'img/basket.png' %}" alt="basket"></a>{% endif %}</li>
    </ul>
</div>

mainapp/templates/mainapp/includes/footer.html
<footer class="footer padding-site">
            <div class="contact-us-block footer-text-block">
                <h3 class="footer-h3">Contact Us</h3>
                <p class="address footer-text-p">
                    132A Bridge Road Richmond VIC&nbsp;Australia.
                </p>
                <p class="contacts footer-text-p">
                    Talk to&nbsp;us on&nbsp;1300&nbsp;132 info@interior.com
                </p>
            </div>
            <div class="useful-info-block footer-text-block">
                <h3 class="footer-h3">
                    Useful Information
                </h3>
                <div class="useful-block-ul">
                    <ul class="useful-block useful-block-1">
                        <li><a href="#">Sales terms</a></li>
                        <li><a href="#">Customer care</a></li>
                        <li><a href="#">Delivery</a></li>
                    </ul>
                    <ul class="useful-block">
                        <li><a href="#">Architect accounts</a></li>
                        <li><a href="#">Careers</a></li>
                        <li><a href="#">Exchanges &amp;&nbsp;returns</a></li>
                    </ul>
                </div>

            </div>
            <div class="subscibe-block footer-text-block">
                <h3 class="footer-h3">
                    Let&rsquo;s Stay in&nbsp;Touch!
                </h3>
                <p class="subscribe footer-text-p">
                    Suscribe to&nbsp;know about our latest news, products and special offers just for suscribers.
                </p>
                <form class="subscibe-form" action="#">
                    <input type="email" placeholder="your email address">
                    <button class="subscibe-button"><i class="fab fa-telegram-plane telegram-button"></i></button>
                </form>
            </div>
            <div class="copyright footer-bottom-text">
                &copy;&nbsp;Copyright&nbsp;&mdash; INTERIOR 2018. All Rights Reserved.
            </div>
            <div class="social-block">

                <a class="social-link-f" href="#">
<i class="fab fa-facebook-f social"></i>
</a>
                <a class="social-link-f" href="#">
<i class="fab fa-twitter social"></i>
</a>
                <a class="social-link-f" href="#">
<i class="fab fa-google-plus-g social"></i>
</a>
                <a class="social-link-f" href="#">
<i class="fab fa-pinterest-p social"></i>
</a>
            </div>
            <div class="terms">
                <a class="footer-bottom-text" href="#">Terms &amp;&nbsp;Conditions</a>
                <p class="footer-bottom-text">/</p>
                <a class="footer-bottom-text" href="#">Privacy policy &amp;&nbsp;Cookies</a>
            </div>
        </footer>

mainapp/templates/mainapp/includes/inc-categories-menu.html
{% load i18n %}
{% url 'mainapp:products' as u %}
<ul class="{{menu_cls}}">
    <li><a class="{% if request.path == u %} active-products-filter{% endif %}" href="{% url 'mainapp:products' %}">{% trans "ALL" %}</a></li>
    {% for object in objects %}
    {% url 'mainapp:products_in_catogory' object.id as u %}
    <li>
        <a href="{% if object.get_url %}{{object.get_url}}{% else %}{% url 'mainapp:products_in_catogory' object.id %}{% endif %}"
           class="{% if request.path == u %}active-products-filter{% endif %}">{{object.title}}</a></li>
    {% endfor %}
</ul>
{% if request.user.is_staff %}
<ul class="{{menu_cls}}">
    <li><a href="{% url 'mainapp:create_product' %}">{% trans "Add new Product" %}</a></li>
</ul>
{% endif %}

mainapp/templates/mainapp/includes/inc-contacts.html
{% load i18n %}
<div class="contacts-c">
                    <div class="contacts-c-text">
                        <a class="show-on-map" href="#" title="{% trans 'Show on map' %}">
<i class="fas fa-map-marker-alt map-marker"></i>
</a>
                        <h2>{% trans cont.title%}</h2>
                        <p class="contacts-c-text-p contacts-c-text-1">
                            {% trans "Phone:" %}
                        </p>
                        <p class="contacts-c-text-p contacts-c-text-2">
                            {% trans cont.phone %}
                        </p>
                        <p class="contacts-c-text-p contacts-c-text-1">
                            {% trans "Email:" %}
                        </p>
                        <p class="contacts-c-text-p contacts-c-text-2">
                            {% if cont.email %}
                            {% trans cont.email %}
                            {% endif %}
                        </p>
                        <p class="contacts-c-text-p contacts-c-text-1">
                            {% trans "Address:" %}
                        </p>
                        <p class="contacts-c-text-p contacts-c-text-3">
                            {% trans cont.address %}
                        </p>
                    </div>
                </div>

mainapp/templates/mainapp/includes/inc-exclusive-products.html
{% load static i18n %}

{% if products %}
{% for product in products %}
<div class='{{div_products_cls}} {{product.pictures.all.0.title}}'>

    <div class="exclusive-product-text">
        <h3>{% trans 'exclusive' %}</h3>
        <h2>{{product.title}}</h2>
        <p>{{product.description}}</p>
        {% include 'mainapp/includes/snippets/snip-btn-orderus.html' %}
    </div>
</div>
{% endfor %}
{% endif %}

mainapp/templates/mainapp/includes/inc-header.html
{% load static i18n %}
<div class="header">
    <a class="logo" href="{% url 'mainapp:index' %}"></a>
    <ul class="menu">
        {% for object in main_menu %}
        <li>
            <a href="{% url object.get_url %}" {% if active == object.title %}class="active-menu" {% endif %}>{% trans object.title %}</a>
        </li>
        {% endfor %}
        <li><a href="{% url 'mainapp:products' %}"><img src="{% static 'img/search.svg' %}" alt="search"></a></li>
        <li>{% if user.is_authenticated %}
            <a href="{% url 'basket:basket_detail' %}"><img src="{% static 'img/basket.png' %}" alt="basket">

                    {% if basket %}
                        {{basket.0.get_total_count|floatformat:0}} шт. на {{ basket.0.get_total_price|floatformat:0 }} руб.
                    {% endif %}

            </a>
            {% endif %}
        </li>
    </ul>
</div>

mainapp/templates/mainapp/includes/inc-messages.html
{% if messages %}
<div class="row">
    <div class="col-sm-6">
        {% for message in messages %}
            <div class="alert alert-success">{{ message }}</div>
        {% endfor %}
    </div>
</div>
{% endif %}

mainapp/templates/mainapp/includes/inc-prod-pic-slider.html
{% load i18n %}
{% if images %}
<div class="product-detail-slider-small">
    {% for image in images %}
        <div class="product-detail-img-small">
            <a href="#"><img src="{{image.image.url}}" alt="{{image.title}}" style="max-height:70px; max-width:70px;"></a>
            {% if request.user.is_staff %}
            <a href="{% url 'mainapp:delete_product_picture' image.id %}">
                {% trans 'Del image' %}
            </a>
            {% endif %}
        </div>
    {% endfor %}
</div>
{% endif %}
{% if request.user.is_staff %}
<div class="btn-add">
    <a href="{% url 'mainapp:create_product_picture' object.id %}" class="btn btn-primary">
        {% trans 'Add image' %}
    </a>
</div>
{% endif %}

mainapp/templates/mainapp/includes/inc-product-detail-view.html
{% extends "mainapp/base.html" %}
{% load i18n %}
{% block header %}
<div class="header-product-content padding-site">
    {% include 'mainapp/includes/inc-header.html' with active='PRODUCTS'%}
    <!--<h2 class="header-content-h2">{% trans "Our Products Range" %}</h2>-->
</div>
{% endblock header %}

{% block content %}
<div class="product-detail-filter-block">
    {% include 'mainapp/includes/inc-categories-menu.html' with menu_cls='products-filter' objects=categories %}
</div>
<div class="product-detail-block padding-site">
    <div class="product-detail-imges">
        <div class="product-detail-img">
            <img src="{{product.pictures.all.0.image.url}}" alt="product.pictures.all.0.title"
                 class="product-detail-img-big">
        </div>
        <!--{% with images=product.pictures.all  %}-->
        {% include 'mainapp/includes/inc-prod-pic-slider.html' with images=product.pictures.all %}
        <!--{% endwith %}-->
    </div>

    <div class="product-detail-text">
        <h2>{{product.title}}</h2>
        <h3>{{product.category}}</h3>
        <p class="price"><span>{% trans 'Price: ' %}</span><span class="price-big">{{product.prices.all.0.price}}</span><span
                class="price-small"> {{product.prices.all.0.currency.title}}</span>
        </p>
        <div class="product-detail-description">
            {{product.description|linebreaks}}
        </div>
        {% if request.user.is_staff %}
            <div class="actions-object">
                <a href="{% url 'mainapp:edit_product' object.id %}">{% trans "Edit Product" %}</a>
            </div>
        {% else %}
            {% if product.prices.all.0.price %}
                <a class="order-button-red" href="{% url 'basket:addinvoiceposition' object.id %}">{% trans 'ORDER US &gt' %};</a>
            {% else %}
                {% trans "Извините, данного товара нет в наличии" %}
            {% endif %}
        {% endif %}
    </div>
</div>
<div class="related-products-block padding-site">
    <div class="trending-products-text">
        <h2>{% trans 'Related Products' %}</h2>
        <a class="explore-all" href="{% url 'mainapp:products' %}">{% trans 'explore all &gt;' %}</a>
    </div>
    {% include 'mainapp/includes/inc-product-listview.html' with products=object_list div_products_cls='trending-products-imgs' %}
    <!--<div class="trending-products-imgs">-->

    <!--</div>-->
</div>
{% endblock content %}

mainapp/templates/mainapp/includes/inc-product-listview.html
{% load static i18n %}
{% if products %}
<div class="{{div_products_cls}}">
	{% for product in products %}
	<div class="trending-product-img">
		<img src="{{product.pictures.all.0.image.url}}" style="width:370px; height:370px;" alt="{{product.title}}">
			<a href= "{% url 'mainapp:product_detail' product.id %}" class="product-text-big">
				<div class="circle-on-active-product-big">
					<img src="{% static 'img/arrow.svg' %}" alt="{% trans 'Go to product' %}">
				</div>
				<div class="text-on-active-product-big">
					<h4>{{product.title}}</h4>
					<p>{{product.description}}</p>
				</div>
			</a>

	</div>
	{% endfor %}
</div>
{% if is_paginated %}
<nav aria-label="...">
	<ul class="pagination">
		{% if page_obj.has_previous %}
		<li class="page-item">
			<a class="page-link" href="?page={{ page_obj.previous_page_number }}" tabindex="-1">Previous</a>
		</li>
		{% else %}
		<li class="page-item disabled">
			<a class="page-link" tabindex="-1">Previous</a>
		</li>
		{% endif%}
		{% for i in paginator.page_range %}
			{% if page_obj.number == i %}
			<li class="page-item active"><a class="page-link" href="?page={{ i }}">{{ i }}<span class="sr-only">(current)</span></a></li>
			{% else %}
			<li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
			{% endif %}
		{% endfor %}
		{% if page_obj.has_next %}
			<li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a></li>
			{% else %}
			<li class="page-item disabled">
				<a class="page-link" tabindex="-1">Next</a></li>
		{% endif %}
	</ul>
</nav>
{% endif %}
{% endif %}

mainapp/templates/mainapp/includes/inc-product-small-info.html
{% load static i18n %}
{% if products %}
<div class={{div_products_cls}}>
    {% for product in products %}
        <div class="product">
            <img src='{{product.pictures.all.0.image.url}}' alt="{% trans 'product.pictures.all.0.image.title' %}">
            <div class="product-text">
                {% include 'mainapp/includes/snippets/snip-go-to-product.html' %}
                <a href="#" class="text-on-active-product">
                    <h4>{{product.title}}</h4>
                    <p>{{product.description}}</p>
                </a>
            </div>
        </div>
    {% endfor %}
</div>
{% endif %}