basket/urls.py
from django.urls import re_path, path
from .views import addInvoicePosition, basketDetailView, minusInvoicePositionCount, dellInvoicePosition, buy
from django.conf import settings
from django.conf.urls.static import static
import os

from pathlib import PurePath
app_name = PurePath(os.path.dirname(__file__)).parts[-1]


urlpatterns = [
    path('invoice/', basketDetailView.as_view(), name='basket_detail'),
    path('addtobasket/<int:pk>/', addInvoicePosition.as_view(), name='addinvoiceposition'),
    path('minustobasket/<int:pk>/', minusInvoicePositionCount.as_view(), name='minusInvoicePositionCount'),
    path('dellInvoicePosition/<int:pk>/', dellInvoicePosition.as_view(), name='dellInvoicePosition'),
    path('buy', buy.as_view(), name = 'buy')
]

gbShop/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.flatpages import views as flat
#import mainapp.views as mainapp

urlpatterns = []

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += [
    path('admin/', admin.site.urls),
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    # path('add/', include('django.contrib.flatpages.urls')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('basket/', include('basket.urls', namespace='basket')),
    path('add/about/', flat.flatpage, {'url': 'add/about/'}, name='about'),
    re_path(r'^', include('mainapp.urls', namespace='mainapp')),
]



#urlpatterns = [
#    path('admin/', admin.site.urls),
#    re_path(r'^$', mainapp.index_view),
#    re_path(r'^index', mainapp.index_view),
#    re_path(r'^products', mainapp.products_view),
#    re_path(r'^contact', mainapp.contact_view),
#]

basket/models.py
from django.db import models
from mainapp.models import Core, Product
from accounts.models import User
from django.utils.translation import gettext_lazy as _
from django.db.models import Sum, F, FloatField, IntegerField

# Create your models here.

class Invoice(Core):

    class Meta:
        verbose_name = _('Счет')
        verbose_name_plural = _('Счета')

    customer = models.ForeignKey(User, verbose_name=_('invoices'), blank=True, null=True, related_name='invoices', on_delete=models.PROTECT)
    date = models.DateTimeField(auto_now_add=True, blank=True)

    @property
    def get_total_price(self):
        return self.invoicepositions.total_price()

    @property
    def get_total_count(self):
        return self.invoicepositions.total_count()


class InvoicePositionManager(models.Manager):

    def get_active(self):
        return self.filter(active=True)

    def get_in_invoice(self, invoice):
        return self.filter(inv=invoice)

    def total_price(self):
        return self.aggregate(summ=Sum(F('price')*F('count'), output_field=FloatField()))['summ']

    def total_count(self):
        return self.aggregate(summ=Sum(F('count'), output_field=IntegerField()))['summ']

class InvoicePosition(Core):

    class Meta:
        verbose_name = _('Позиция счета')
        verbose_name_plural = _('Позиция счета')

    inv = models.ForeignKey(Invoice, verbose_name=_('invoicepositions'), null=False, related_name='invoicepositions', on_delete=models.PROTECT)
    prod = models.ForeignKey(Product, null=False, on_delete=models.PROTECT)
    price = models.DecimalField(max_digits=10, default=0, decimal_places=0)
    count = models.PositiveIntegerField(default=0, null=False, blank=True)
    object = InvoicePositionManager()


    @property
    def total_price(self):
        return float(int(self.count or 0) * float(self.price or 0))

basket/views.py
from django.shortcuts import render
from django.contrib.admin.models import ADDITION, LogEntry
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.contenttypes.models import ContentType
from django.contrib.messages.views import SuccessMessageMixin
from django.db.models import F, Count
from django.http import HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.utils.translation import ugettext_lazy as _
from django.views.generic import (CreateView, DeleteView, DetailView, ListView,
                                  RedirectView, UpdateView)
from django.views.generic.base import ContextMixin
from django.views.generic.edit import FormView
from .models import Invoice, InvoicePosition


# Create your views here.

class basketDetailView(LoginRequiredMixin, SuccessMessageMixin, DetailView):
    """
    Отображение содержимого корзины :model:`mainapp.Invoice`
    """
    model = Invoice

    def get_object(self, queryset=None):
        object, created = Invoice.objects.get_or_create(customer=self.request.user, active=True)
        return object



class addInvoicePosition(LoginRequiredMixin, UpdateView):

    fields = ('count',)
    model = InvoicePosition
    success_url = reverse_lazy('basket:basket_detail')

    def get(self, request, *args, **kwargs):
        print('+++++++++++++++++++')
        invoice, created = Invoice.objects.get_or_create(customer=self.request.user, active=True) # создаем или получаем корзину пользователя
        invoice_position, created = InvoicePosition.objects.get_or_create(inv=invoice, prod_id=self.kwargs['pk'], active=True) # создаем или получаем строку заказа в корзине
        invoice_position.count += 1
        invoice_position.price = invoice_position.prod.prices.first().price or 0
        invoice_position.save()
        return HttpResponseRedirect(self.success_url)


    def form_invalid(self, form):
        print(form.errors)


    def form_valid(self, form):
        # count = form.instance.count + 1
        # print(count)
        # invoice, created = Invoice.objects.get_or_create(customer=self.request.user, active=True) # создаем или получаем корзину пользователя
        # invoice_position, created = InvoicePosition.objects.get_or_create(inv=invoice, prod_id=self.kwargs['pk'], active=True) # создаем или получаем строку заказа в корзине
        # invoice_position.count += 1
        self.object.count += 1
        return super().form_valid(form)


class minusInvoicePositionCount(LoginRequiredMixin, UpdateView):
    fields = ('count',)
    model = InvoicePosition
    success_url = reverse_lazy('basket:basket_detail')

    def get(self, request, *args, **kwargs):
        print('------------------------')
        invoice, created = Invoice.objects.get_or_create(customer=self.request.user, active=True) # создаем или получаем корзину пользователя
        invoice_position, created = InvoicePosition.objects.get_or_create(inv=invoice, prod_id=self.kwargs['pk'], active=True) # создаем или получаем строку заказа в корзине
        if invoice_position.count > 0:
            invoice_position.count -= 1
        invoice_position.save()
        return HttpResponseRedirect(self.success_url)

    def form_valid(self, form):
        if self.object.count > 0:
            self.object.count -= 1
        return super().form_valid(form)


class dellInvoicePosition(LoginRequiredMixin, DeleteView):
    model = InvoicePosition

    def get_success_url(self):
        return reverse('basket:basket_detail')


class buy(LoginRequiredMixin, UpdateView):
    model = Invoice
    fields = ('active', )
    template_name = 'basket/invoice_detail.html'

    def get_success_url(self):
        return reverse('basket:basket_detail')

    def get_object(self, queryset=None):
        object, created = Invoice.objects.get_or_create(customer=self.request.user, active=True)
        print(object)
        return object

    def form_valid(self, form):
        obj = self.get_object()
        obj.active = False
        return super().form_valid(form)

basket/templates/basket/invoice_detail.html
{% extends "mainapp/base.html" %}
{% load i18n %}
{% block header %}
<div class="header-content padding-site">
    {% include 'mainapp/includes/inc-header.html'%}
    <h2 class="header-content-h2">{% trans "You basket chart" %}</h2>
</div>
{% endblock header %}
{% block content %}
<div class="catalogue">
    <div class="row">
        {% if object.active and object.invoicepositions.count %}
        {% include './invoiceposition_form.html' with object_list=object.invoicepositions.all %}
        <p class="total_summ">{% trans 'Total price' %} <span>{{ object.get_total_price }}</span></p>
        <form method="post" action="{% url 'basket:buy' %}">
            {% csrf_token %}
            <input type="submit" value="{% trans 'Buy' %}" class="btn btn-primary">
        </form>
        {% else %}
        <p>{% trans 'Корзина пуста' %}</p>
        {% endif %}
    </div>
</div>
{% endblock content %}

basket/templates/basket/invoiceposition_confirm_delete.html
{% extends "mainapp/base.html" %}
{% load i18n static %}
{% block title %}{{object.verbose_name}}{% endblock title %}

{% block header %}
<div class="header-content padding-site">
    {% include 'mainapp/includes/inc-header.html'%}
    <h2 class="header-content-h2">{% trans "Delete Product from chart ?" %}</h2>
</div>
{% endblock header %}

{% block content %}
<h4>{{ object.prod.title }}</h4>
<img src="{{object.prod.pictures.all.0.image.url}}" alt="{{object.prod.pictures.all.0.image.title}}">
<div class="login-block-n padding-site">
    <div class="login-block-content">
        <form method="post" class="login-form form-group">
            {% csrf_token %}
            <a href="{% url 'basket:basket_detail' %}" class="btn btn-primary">{% trans 'No' %}</a>
            <button type="submit" name='delete' class="btn btn-primary">{% trans 'Yes' %}</button>
        </form>
    </div>
</div>
{% endblock content %}

basket/templates/basket/invoiceposition_form.html
{% load i18n %}

<table class="table table-bordered">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Product</th>
            <th scope="col">Price</th>
            <th scope="col">Count</th>
            <th scope="col">TotalPrice</th>
            <th scope="col">Remove from chart</th>
        </tr>
    </thead>
    <tbody>
    {% for object in object_list %}
        <tr>
            <th scope="row">{{ forloop.counter }}</th>
            <td>{{ object.prod }}</td>
            <td>{{ object.price }}</td>
            <td>
                <form method="post" action="{% url 'basket:minusInvoicePositionCount' object.id %}">
                    {% csrf_token %}
                    <input type="submit" value="{% trans '-' %}" class="btn btn-primary">
                </form> {{ object.count }}
                <form method="post" action="{% url 'basket:addinvoiceposition' object.id %}">
                    {% csrf_token %}
                    <input type="submit" value="{% trans '+' %}" class="btn btn-primary">
                </form>
            </td>
            <td>{{ object.total_price }}</td>
            <td><a href="{% url 'basket:dellInvoicePosition' object.id %}">{% trans 'Remove' %}</a></td>
        </tr>
    {% endfor %}
    </tbody>
</table>