accounts/urls.py
from django.urls import re_path, path
from .views import Login, Logout, CreateProfile, profileView, editProfileView, createAvatarView, deleteAvatarView, VerificationUser
from django.conf import settings
from django.conf.urls.static import static
import os
#app_name = os.path.dirname(__file__).rsplit('/', 1)[1]
from pathlib import PurePath
app_name = PurePath(os.path.dirname(__file__)).parts[-1]

#app_name = 'accounts'

urlpatterns = [
    path('login/', Login.as_view(), name='login'),
    path('logout/', Logout.as_view(), name='logout'),
    path('profile/', profileView.as_view(), name='profile'),
    path('editprofile/',  editProfileView.as_view(), name='editProfile'),
    path('createprofile/',  CreateProfile.as_view(), name='createProfile'),
    path('createavatar/<int:related_obj>/',  createAvatarView.as_view(), name='createAvatar'),
    path('deleteAvatar/<int:pk>/',  deleteAvatarView.as_view(), name='deleteAvatar'),
    path('verify/<str:email>/<str:activation_key>/', VerificationUser.as_view(), name='verify')
]

basket/urls.py
from django.urls import re_path, path
from .views import addInvoicePosition, basketDetailView, minusInvoicePositionCount, dellInvoicePosition, buy
from django.conf import settings
from django.conf.urls.static import static
import os

from pathlib import PurePath
app_name = PurePath(os.path.dirname(__file__)).parts[-1]


urlpatterns = [
    path('invoice/', basketDetailView.as_view(), name='basket_detail'),
    path('addtobasket/<int:pk>/', addInvoicePosition.as_view(), name='addinvoiceposition'),
    path('minustobasket/<int:pk>/', minusInvoicePositionCount.as_view(), name='minusInvoicePositionCount'),
    path('dellInvoicePosition/<int:pk>/', dellInvoicePosition.as_view(), name='dellInvoicePosition'),
    path('buy', buy.as_view(), name = 'buy')
]

gbShop/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.flatpages import views as flat
#import mainapp.views as mainapp

urlpatterns = []

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += [
    path('admin/', admin.site.urls),
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    # path('add/', include('django.contrib.flatpages.urls')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('basket/', include('basket.urls', namespace='basket')),
    path('add/about/', flat.flatpage, {'url': 'add/about/'}, name='about'),
    re_path(r'^', include('mainapp.urls', namespace='mainapp')),
]



#urlpatterns = [
#    path('admin/', admin.site.urls),
#    re_path(r'^$', mainapp.index_view),
#    re_path(r'^index', mainapp.index_view),
#    re_path(r'^products', mainapp.products_view),
#    re_path(r'^contact', mainapp.contact_view),
#]

mainapp/urls.py
from django.urls import re_path, path
from .views import indexView, contactListView, productListView, productDetailView, productCreateView, productEditView, productPictureCreateView, productPictureDeleteView
from django.conf import settings
from django.conf.urls.static import static
import os
#app_name = os.path.dirname(__file__).rsplit('/', 1)[1]
app_name = 'mainapp'

urlpatterns = [
    path('products/category/<int:pk>/', productListView.as_view(), name='products_in_catogory'),
    path('products/<int:pk>/', productDetailView.as_view(), name='product_detail'),
    path('products/', productListView.as_view(), name='products'),
    # path('search/', searchView.as_view(), name='search'),
    path('addnewproduct', productCreateView.as_view(), name='create_product'),
    path('addnewproduct/category/<int:cat_id>/',  productCreateView.as_view(), name='create_product'),
    path('editproduct/<int:pk>/', productEditView.as_view(), name='edit_product'),
    path('createprodpicture/<int:related_obj>/',  productPictureCreateView.as_view(), name='create_product_picture'),
    path('deleteprodpicture/<int:pk>/',  productPictureDeleteView.as_view(), name='delete_product_picture'),
    path('contacts', contactListView.as_view(), name='contacts'),
    re_path(r'^$', indexView.as_view(), name='index'),
    path(' ', indexView.as_view(), name='index'),
]

accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils import timezone
from mainapp.models import Core, Picture
from django.utils.translation import gettext_lazy as _
# Create your models here.

class User(AbstractUser, Core):
    """ Модель User"""
    class Meta:
        verbose_name = _('Пользователь')
        verbose_name_plural = _('Пользователи')

    #is_manager = models.BooleanField(_('Менеджер'), default=False) #может управлять товарами магазина без админ панели
    activation_key = models.CharField(max_length=128, blank=True)
    # Период активации
    activation_key_expires = models.DateTimeField(default=timezone.now() +
                                                          timezone.timedelta(hours=48))

    def is_activation_key_expired(self):
        return timezone.now() > self.activation_key_expires



class Avatar(Picture):
    """ Модель Avatar"""
    class Meta:
        verbose_name = _('Аватар')
        verbose_name_plural = _('Аватары')
        proxy = True

accounts/forms.py
import hashlib
import random

from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from .models import User


class UserLoginForm(AuthenticationForm):
    class Meta:
        model = User
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(UserLoginForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''


class UserRegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email')

    def __init__(self, *args, **kwargs):
        super(UserRegistrationForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''

    def save(self, commit=True):
        user = super().save(commit)
        user.is_active = False
        salt = hashlib.sha1(str(random.random()).encode('utf8')).hexdigest()[:6]
        user.activation_key = hashlib.sha1((user.email + salt).encode('utf8')).hexdigest()
        user.save()
        return user

accounts/views.py
from django.contrib.auth.views import LoginView, LogoutView, TemplateView
from django.contrib.auth.mixins import UserPassesTestMixin, LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.core.mail import send_mail
from django.utils.translation import ugettext_lazy as _
from django.contrib import messages, auth

from django.conf import settings
from .models import User, Avatar
from django.views.generic  import DetailView, CreateView, DeleteView, UpdateView
from django.urls import reverse, reverse_lazy
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.http import HttpResponseRedirect, Http404
from .forms import UserLoginForm, UserRegistrationForm


class Login(SuccessMessageMixin, UserPassesTestMixin, LoginView):
    """docstring for LoginView"""
    template_name = 'accounts/login.html'
    success_message = _('Вы вошли в систему')
    form_class = UserLoginForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = _('Log in')
        return context

    def test_func(self):
        return not self.request.user.is_authenticated

    def handle_no_permission(self):
        return HttpResponseRedirect('/')

    def get_next_page(self):
        next_page = super().get_next_page()
        if next_page:
            messages.success(self.request, self.success_message)
        return next_page

    # def form_valid(self, form):
    #     user = self.request.user
    #     if user and user.is_active:



class Logout(LoginRequiredMixin, LogoutView):
    """docstring for logoutView"""
    success_message = _('Вы вышли из системы')

    def get_next_page(self):
        next_page = super().get_next_page()
        if next_page:
            messages.success(self.request, self.success_message)
        return next_page


def send_verify_email(user):
    # код
    # ссылка для подтверждения
    verify_link = reverse('accounts:verify', args=[user.email, user.activation_key])
    title = f'Подтверждение учетной записи {user.username}'
    message = f'Для подтверждения учетной записи {user.username} \
    на портале {settings.DOMAIN_NAME} перейдите по ссылке: \
    \n{settings.DOMAIN_NAME}{verify_link}'

    return send_mail(title, message, settings.EMAIL_HOST_USER, [user.email], fail_silently=False)


class CreateProfile(SuccessMessageMixin, CreateView):
    """docstring for RegisterProfile"""
    template_name = 'accounts/register.html'
    model = User
    form_class = UserRegistrationForm
    success_url = '/'
    success_message = _('На Ваш почтовый ящик, указанный при регистрации было выслано письмо с ссылкой для активации аккаунта')
    error_message = _('К сожалению, возникла проблема с отправкой Вам письма с кодом активации. Проверьте правильность введенного адреса и попробуйте заново')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = _('Register')
        return context


    def form_valid(self, form):
        response = super().form_valid(form)
        user = form.save()
        print(user.first_name)
        if send_verify_email(user):
            print('Письмо отправлено')
            return response
        else:
            print('Ошибка отправки')
            messages.error(self.request, self.error_message)
            return HttpResponseRedirect('/')


class VerificationUser(TemplateView):
    template_name = 'accounts/verification.html'

    def get(self, request, *args, **kwargs):
        email = kwargs.get('email')
        activation_key = kwargs.get('activation_key')
        user = User.objects.get(email=email)
        print(email)
        print(activation_key)
        print(user.activation_key)
        print (user.is_activation_key_expired())
        print (user.activation_key_expires)
        if user.activation_key == activation_key and not user.is_activation_key_expired():
            print('Зашел?')
            user.is_active = True
            user.save()
            auth.login(request, user)
        return super().get(request, *args, **kwargs)
        # print('Конец')
        # raise Http404


class profileView(LoginRequiredMixin, DetailView):
    """docstring for AddView"""
    model = User

    def get_object(self, queryset=None):
        return self.request.user


class editProfileView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    """docstring for AddView"""
    fields = ('username', 'first_name', 'last_name', 'email', 'description', 'password')
    form = UserChangeForm
    model = User
    # success_url =  '/auth/profile/'
    success_message = _('Ваши данные успешно изменены')

    def get_success_url(self):
        self.object.set_password(self.object.password)
        self.object.save()
        return reverse_lazy('accounts:profile')

    def get_object(self, queryset=None):
        return self.request.user

    def save(self, commit=True):
        self.object.set_password(self.object.password)
        self.object.save()
        return self.object


class createAvatarView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    """docstring for createAvatarView"""
    fields = ('image', 'title')
    model = Avatar
    success_message = _('Аватар добавлен')

    def form_valid(self, form):
        form.instance.related_obj = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('accounts:profile')


class deleteAvatarView(LoginRequiredMixin, UserPassesTestMixin, SuccessMessageMixin, DeleteView):
    """docstring for DelView"""
    model = Avatar
    success_message = _('Аватар был удален')

    def test_func(self):
        pk = self.kwargs.get('pk', 0)
        return self.request.user.pictures.filter(id=pk).exists()

    def get_success_url(self):
        return reverse('accounts:profile')

accounts/templates/accounts/avatar_confirm_delete.html
{% extends "mainapp/base.html" %}
{% load i18n %}
{% block title %}{{object_list.model.verbose_name_plural}}{% endblock title %}

{% block header %}
<div class="header-content padding-site">
    {% include 'mainapp/includes/inc-header.html' %}
    <h2 class="header-content-h2">
        {% trans "Delete user Avatar" %}
    </h2>
</div>
{% endblock header %}

{% block content %}
<div class="product-detail-block padding-site">

    <div class="login-block-content">
        <form method="post" class="login-form form-group">
            {% csrf_token %}
            <img src="{{object.image.url}}" alt="{{object.image.title}}">
            <button type="submit" class="btn btn-primary">{% trans 'Confirm delete avatar' %}</button>
        </form>
    </div>
</div>
{% endblock content %}

accounts/templates/accounts/avatar_form.html
{% extends "mainapp/base.html" %}
{% load i18n %}
{% block title %}{{object_list.model.verbose_name_plural}}{% endblock title %}

{% block header %}
<div class="header-content padding-site">
    {% include 'mainapp/includes/inc-header.html' %}
    <h2 class="header-content-h2">
        {% trans "User add Avatar" %}
    </h2>
</div>
{% endblock header %}

{% block content %}
<div class="product-detail-block padding-site">

    <div class="login-block-content">
        <form method="post" class="login-form form-group" enctype="multipart/form-data">
            {% csrf_token %}
            {{form.as_p}}
            <button type="submit" class="btn btn-primary">{% trans 'Save changes' %}</button>
        </form>
    </div>
</div>
{% endblock content %}

accounts/templates/accounts/login.html
{% extends "mainapp/base.html" %}{% load i18n %}
{% block title %}{{object_list.model.verbose_name_plural}}{% endblock title %}

{% block header %}
<div class="header-content padding-site">
    {% include 'mainapp/includes/inc-header.html' with active='Log in'%}
    <h2 class="header-content-h2">{% trans "Log In" %}</h2>

</div>
{% endblock header %}

{% block content %}
<div class="login-block-n">
    <div class="login-block-content">
        <form action="{% url 'accounts:login' %}" method="post" class="login-form form-group">
            {% csrf_token %}
            {{ form.as_p }}
        <button type="submit" class="btn btn-primary">{% trans 'Log in' %}</button>
            <a href="{% url 'accounts:createProfile' %}" class="btn btn-primary">{% trans 'Registation' %}</a>
        </form>
    </div>
</div>
{% endblock content %}

accounts/templates/accounts/register.html
{% extends "mainapp/base.html" %}
{% load i18n %}
{% block title %}{{object_list.model.verbose_name_plural}}{% endblock title %}

{% block header %}
<div class="header-content padding-site">
    {% include 'mainapp/includes/inc-header.html' with active=user.first_name %}
    <h2 class="header-content-h2">{% trans "User registration form" %}</h2>
</div>
{% endblock header %}

{% block content %}
<div class="product-detail-block padding-site">
    <div class="login-block-content">
        <form method="post" class="login-form form-group">
            {% csrf_token %}
            {{form.as_p}}
            <button type="submit" class="btn btn-primary">{% trans 'Registration' %}</button>
        </form>
    </div>
</div>
{% endblock content %}

accounts/templates/accounts/user_detail.html
{% extends "mainapp/base.html" %}
{% load i18n %}
{% block title %}{{object_list.model.verbose_name_plural}}{% endblock title %}

{% block header %}
<div class="header-content padding-site">
    {% include 'mainapp/includes/inc-header.html' with active=user.first_name %}
    <h2 class="header-content-h2">{% trans "User profile" %}</h2>

</div>
{% endblock header %}

{% block content %}
<div class="profile-detail-block padding-site">
    <div class="product-detail-imges">
        <div class="product-detail-img">
            <img src="{{object.pictures.all.0.image.url}}" alt="object.pictures.all.0.title" class="avatar-img-big">
        </div>
        <!--{% with images=product.pictures.all  %}-->
        {% include 'accounts/includes/inc-user-avatars.html' with images=object.pictures.all %}
        <!--{% endwith %}-->
    </div>

    <div class="product-detail-text">
        <p>{% trans 'fullname: ' %}</p>
        <h2>{{object.first_name}} {{object.last_name}}</h2>
        <p>{% trans 'username: ' %}</p>
        <h2>{{object.username}}</h2>
        <p>{% trans 'email: ' %}</p><h3>{{object.email}}</h3>
        {% if object.description%}
        <p>{% trans 'About: ' %}</p>
        <div class="product-detail-description">
            {{object.description|linebreaks}}
        </div>
        {% endif %}
        <a href="{% url 'accounts:editProfile' %}" class="btn btn-primary">{% trans 'Change profile' %}</a>

        <!--<a href="{% url 'accounts:editProfile' %}" class="btn btn-primary">{% trans 'Change password' %}</a>-->
    </div>
</div>
{% endblock content %}

accounts/templates/accounts/user_form.html
{% extends "mainapp/base.html" %}
{% load i18n %}
{% block title %}{{object_list.model.verbose_name_plural}}{% endblock title %}

{% block header %}
<div class="header-content padding-site">
    {% include 'mainapp/includes/inc-header.html' with active=user.first_name %}
    <h2 class="header-content-h2">{% if request.path == '/auth/createprofile/' %}
        {% trans "User create profile" %}
        {% else %}
        {% trans "User change profile" %}
        {% endif %}
    </h2>

</div>
{% endblock header %}

{% block content %}
<div class="product-detail-block padding-site">
    <!--<div class="product-detail-imges">-->
        <!--<div class="product-detail-img">-->
            <!--<img src="{{object.pictures.all.0.image.url}}" alt="object.pictures.all.0.title"-->
                 <!--class="product-detail-img-big">-->
        <!--</div>-->
        <!--&lt;!&ndash;{% with images=product.pictures.all  %}&ndash;&gt;-->
        <!--{% include 'mainapp/includes/inc-prod-pic-slider.html' with images=object.pictures.all|slice:"1:" %}-->
        <!--&lt;!&ndash;{% endwith %}&ndash;&gt;-->
    <!--</div>-->

    <div class="login-block-content">
        <form method="post" class="login-form form-group">
            {% csrf_token %}
            {{form.as_p}}
            <button type="submit" class="btn btn-primary">{% trans 'Save changes' %}</button>
            <!--<a href="{% url 'accounts:editProfile' %}">-->
                <!---->
            <!--</a>-->
        </form>
    </div>
</div>
{% endblock content %}

accounts/templates/accounts/verification.html
{% extends "mainapp/base.html" %}
{% load i18n %}
{% block title %}{{object_list.model.verbose_name_plural}}{% endblock title %}

{% block header %}
<div class="header-content padding-site">
    {% include 'mainapp/includes/inc-header.html' with active=user.first_name %}
    <h2 class="header-content-h2">{% trans "User registration form" %}</h2>
</div>
{% endblock header %}

{% block content %}
<div class="product-detail-block padding-site">
    <div class="login-block-content">
        {% if user %}
        <h3>Поздравляем!</h3>
        <br>
        <h4>Пользователь {{user.username}} подтвержден.</h4>
        {% else %}
        <h3>Верификация не пройдена.</h3>
        {% endif %}
        <br>
        <a href="{% url 'mainapp:index' %}" class="btn btn-primary">{% trans 'На главную' %}</a>
    </div>
</div>
{% endblock content %}