basket/urls.py
from django.urls import re_path, path
from .views import addInvoicePosition, basketDetailView, minusInvoicePositionCount, dellInvoicePosition, buy
from django.conf import settings
from django.conf.urls.static import static
import os

from pathlib import PurePath
app_name = PurePath(os.path.dirname(__file__)).parts[-1]


urlpatterns = [
    path('invoice/', basketDetailView.as_view(), name='basket_detail'),
    path('addtobasket/<int:pk>/', addInvoicePosition.as_view(), name='addinvoiceposition'),
    path('minustobasket/<int:pk>/', minusInvoicePositionCount.as_view(), name='minusInvoicePositionCount'),
    path('dellInvoicePosition/<int:pk>/', dellInvoicePosition.as_view(), name='dellInvoicePosition'),
    path('buy', buy.as_view(), name = 'buy')
]

gbShop/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.flatpages import views as flat
#import mainapp.views as mainapp

urlpatterns = []

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += [
    path('admin/', admin.site.urls),
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    # path('add/', include('django.contrib.flatpages.urls')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('basket/', include('basket.urls', namespace='basket')),
    path('add/about/', flat.flatpage, {'url': 'add/about/'}, name='about'),
    re_path(r'^', include('mainapp.urls', namespace='mainapp')),
]



#urlpatterns = [
#    path('admin/', admin.site.urls),
#    re_path(r'^$', mainapp.index_view),
#    re_path(r'^index', mainapp.index_view),
#    re_path(r'^products', mainapp.products_view),
#    re_path(r'^contact', mainapp.contact_view),
#]

mainapp/urls.py
from django.urls import re_path, path
from .views import indexView, contactListView, productListView, productDetailView, productCreateView, productEditView, productPictureCreateView, productPictureDeleteView
from django.conf import settings
from django.conf.urls.static import static
import os
#app_name = os.path.dirname(__file__).rsplit('/', 1)[1]
app_name = 'mainapp'

urlpatterns = [
    path('products/category/<int:pk>/', productListView.as_view(), name='products_in_catogory'),
    path('products/<int:pk>/', productDetailView.as_view(), name='product_detail'),
    path('products/', productListView.as_view(), name='products'),
    # path('search/', searchView.as_view(), name='search'),
    path('addnewproduct', productCreateView.as_view(), name='create_product'),
    path('addnewproduct/category/<int:cat_id>/',  productCreateView.as_view(), name='create_product'),
    path('editproduct/<int:pk>/', productEditView.as_view(), name='edit_product'),
    path('createprodpicture/<int:related_obj>/',  productPictureCreateView.as_view(), name='create_product_picture'),
    path('deleteprodpicture/<int:pk>/',  productPictureDeleteView.as_view(), name='delete_product_picture'),
    path('contacts', contactListView.as_view(), name='contacts'),
    re_path(r'^$', indexView.as_view(), name='index'),
    path(' ', indexView.as_view(), name='index'),
]

mainapp/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _

# Create your models here.
class Core(models.Model):
    """ Базовый класс моделей"""
    title = models.CharField(_('Название'), max_length=255, blank=True, null=True)
    description = models.TextField(_('Описание'), blank=True, null=True)
    sort = models.IntegerField(_('Сортировка'), default=0, blank=True, null=True)
    active = models.BooleanField(_('Активно'), default=False)

    class Meta:
        ordering = ['sort']

    def __str__(self):
        return f'{self.title}'

    @property
    def verbose_name(self):
        return self._meta.verbose_name

    @property
    def verbose_name_plural(self):
        return self._meta.verbose_name_plural


class ProductCategory(Core):
    """Категория товара"""
    class Meta:
        verbose_name = _('Продуктовая категория')
        verbose_name_plural = _('Продуктовые категории')


class ProductManufacturer(Core):
    """Производитель товара"""
    class Meta:
        verbose_name = _('Производитель')
        verbose_name_plural = _('Производители')


class Product(Core):
    """Продукт/товар"""
    class Meta:
        verbose_name = _('Продукт')
        verbose_name_plural = _('Продукты')

    category = models.ForeignKey(ProductCategory, null=True, on_delete=models.SET_NULL)
    manufacturer = models.ForeignKey(ProductManufacturer, null=True, on_delete=models.SET_NULL)


class PriceCurrency(Core):
    """Класс валюты"""
    class Meta:
        verbose_name = _('Валюта')
        verbose_name_plural = _('Валюты')


class ProductPrice(Core):
    """Цена товара"""
    price = models.DecimalField(_('Цена'), default=0, decimal_places=0, max_digits=20)
    currency = models.ForeignKey(PriceCurrency, null=True, on_delete=models.SET_NULL)
    prod = models.ForeignKey(Product, verbose_name=_('Цены'), related_name='prices', blank=True, null=True, on_delete=models.CASCADE)

    class Meta:
        verbose_name = _('Цена на продукт')
        verbose_name_plural = _('Цены на продукты')


class Picture(Core):
    """Картинки для объектов"""
    class Meta:
        verbose_name = _('Картинка')
        verbose_name_plural = _('Картинки')

    image=models.ImageField(upload_to='images')
    related_obj=models.ForeignKey(Core, verbose_name=_('pictures'), blank=True, null=True, related_name='pictures', on_delete=models.CASCADE)


class Contact(Core):
    """Контакты"""

    class Meta:
        verbose_name = _('Контакт')
        verbose_name_plural = _('Контакты')

    phone = models.CharField(_('Телефон'), max_length=14)
    email = models.EmailField(_('Email'), max_length=64, null=True, blank=True)
    address = models.CharField(_('Адрес'), max_length=255)

mainapp/views.py
from django.shortcuts import render_to_response
from django.contrib.auth.mixins import UserPassesTestMixin, LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from .models import Product, Picture, ProductCategory, ProductManufacturer, ProductPrice, Contact
from django.views.generic import ListView, DetailView, CreateView, DeleteView, UpdateView, View
from django.utils.translation import ugettext_lazy as _


class indexView(ListView):
    """класс для представления index_view"""
    template_name = 'mainapp/index.html'
    model = Product

    def get_context_data(self, **kwargs):
        response = super().get_context_data(**kwargs)
        # response.update({'main_menu': main_menu})
        return response



class productDetailView(DetailView):
    """класс для представления product_detail_view"""
    model = Product
    template_name = 'mainapp/includes/inc-product-detail-view.html'

    def get_context_data(self, **kwargs):
        response = super().get_context_data(**kwargs)
        response['categories']= ProductCategory.objects.all()
        obj = response.get('object', None)
        obj_id = getattr(obj, 'id', 0)
        cat_id = getattr(obj, 'category', 0)

        product_list = Product.objects.exclude(id=obj_id).filter(category=cat_id).order_by('sort')

        response.update({'object_list': product_list })
        return response

class productCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):

    fields = '__all__'
    model = Product
    success_message = _('Продукт успешно добавлен')

    # def get_form_kwargs(self):
    #     form_kwargs = super().get_form_kwargs()
    #     form_kwargs['initial'] = {}
    #     form_kwargs['initial']['category'] = self.kwargs.get['cat_id']
    #     return form_kwargs

    def get_success_url(self):
        return reverse_lazy('mainapp:product_detail',args=(self.object.id or 0,))

class productEditView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    """docstring for AddView"""
    fields = '__all__'
    model = Product
    success_message = _('Данные продукта успешно изменены')

    def get_success_url(self):
        return reverse_lazy('mainapp:product_detail',args=(self.object.id or 0,))


class productPictureCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    """docstring for createAvatarView"""
    fields = ('image', 'title', 'active')
    model = Picture
    success_message = _('Изображение товара успешно добавлено')

    def form_valid(self, form):
        form.instance.related_obj_id = self.kwargs.get('related_obj')
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('mainapp:product_detail',args=(self.object.related_obj.id or 0,))

    def get_context_data(self, **kwargs):
        response = super().get_context_data(**kwargs)
        response['related_obj']= self.kwargs.get('related_obj')
        return response


class productPictureDeleteView(LoginRequiredMixin, SuccessMessageMixin, DeleteView):
    """docstring for DelView"""
    model = Picture
    success_message = _('Изображение товара было удалено')

    def get_success_url(self):
        return reverse_lazy('mainapp:product_detail',args=(self.object.related_obj.id or 0,))

#def index_view(request):
#    context = {'main_menu': main_menu, 'products': Product.objects.all()}
#    return render_to_response('mainapp/index.html', context)

#def products_view(request):
#    context = {'main_menu': main_menu, 'products': Product.objects.all()}
#    return render_to_response('mainapp/products-page.html', context)

class contactListView(ListView):
    template_name = 'mainapp/contact.html'
    model = Contact

    def get_context_data(self, **kwargs):
        response = super().get_context_data(**kwargs)
        #response.update({'main_menu': main_menu})
        return response

#def contact_view(request):
#    context = {'main_menu': main_menu, 'contacts': Contact.objects.all()}
#    return render_to_response('mainapp/contact.html', context)


class productListView(ListView):
    """класс для представления products_view"""
    # template_name = 'mainapp/product_detail.html'
    model = Product
    paginate_by = 3

    def get_context_data(self, **kwargs):
        response = super().get_context_data(**kwargs)
        response['categories']= ProductCategory.objects.all()
        return response

    def get_queryset(self):
        response = super().get_queryset()
        if hasattr(self, 'filter'):
            response = response.filter(**self.filter)
        # if 'search' in self.request.GET:
        #     search = self.request.GET.get('search', '')
        #     if search: # выдаю ВСЕ варианты поиска в категории ИЛИ в имени товара ИЛИ в его описании, оператор "|", склеивающий три запроса вместе
        #         response = (response.filter(**{'category__title__icontains': search}) |
        #                     response.filter(**{'title__icontains': search}) |    # icontains НЕ работает для sqllite
        #                     response.filter(**{'title__contains': search.capitalize() }) |
        #                     response.filter(**{'description__icontains': search}))
        return response

    def get(self, request, *args, **kwargs):
        pk = kwargs.pop('pk', None)
        if pk:
            self.filter = {'category': pk}
        return super().get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        search= self.request.POST.get('search')
        if search: # глупо, но я передаю полученный запрос по каналу GET в контроллер вида allView
            self.filter = {'title__contains': search}
        return super().get(request, *args, **kwargs)

mainapp/templates/mainapp/base.html
<!DOCTYPE html>
{% load static i18n %}
<html>
    <head>
        <meta charset= "utf-8">
        <title>
        {% block title %}{% trans "Interior Store" %}{% endblock title %}
        </title>
        {% block css %}

        <link rel= "stylesheet" href= "{% static 'css/style.css' %}?v={{ VERSION }}" >
        <!--<link rel= "stylesheet" href= "{% static 'css/bootstrap.css' %}?v={{ VERSION }}" >-->
        <link rel= "stylesheet" href= "{% static 'fonts/font-awesome/css/all.css' %}?v={{ VERSION }}" >
        <link rel= "stylesheet" href= "{% static 'fonts/font-awesome/css/montserrat.css' %}?v={{ VERSION }}" >
        {% endblock css %}
    {% block js %}
    {% endblock js %}
    </head>
<body>
<div class="container">
    <div class ="content">
    {% block header %}
            <div class="slider padding-site">
				{% include 'mainapp/includes/inc-header.html' %}
			</div>
    {% endblock header%}
    {% block messages %}
        {% include 'mainapp/includes/inc-messages.html' %}
    {% endblock messages%}
    {% block content %}
    {% endblock content%}
</div >
    {% block footer %}
<footer class="footer padding-site">
            <div class="contact-us-block footer-text-block">
                <h3 class="footer-h3">{% trans "Contact Us" %}</h3>
                <p class="address footer-text-p">
                    {% trans "132A Bridge Road Richmond VIC&nbsp;Australia." %}
                </p>
                <p class="contacts footer-text-p">
                    {% trans "Talk to&nbsp;us on&nbsp;1300&nbsp;132 info@interior.com" %}
                </p>
            </div>
            <div class="useful-info-block footer-text-block">
                <h3 class="footer-h3">
                    {% trans "Useful Information" %}
                </h3>
                <div class="useful-block-ul">
                    <ul class="useful-block useful-block-1">
                        <li><a href="#">{% trans "Sales terms" %}</a></li>
                        <li><a href="#">{% trans "Customer care" %}</a></li>
                        <li><a href="#">{% trans "Delivery" %}</a></li>
                    </ul>
                    <ul class="useful-block">
                        <li><a href="#">{% trans "Architect accounts" %}</a></li>
                        <li><a href="#">{% trans "Careers" %}</a></li>
                        <li><a href="#">{% trans "Exchanges &amp;&nbsp;returns" %}</a></li>
                    </ul>
                </div>

            </div>
            <div class="subscibe-block footer-text-block">
                <h3 class="footer-h3">
                    {% trans "Let&rsquo;s Stay in&nbsp;Touch!" %}
                </h3>
                <p class="subscribe footer-text-p">
                    {% trans "Suscribe to&nbsp;know about our latest news, products and special offers just for suscribers." %}
                </p>
                <form class="subscibe-form" action="#">
                    <input type="email" placeholder="your email address">
                    <button class="subscibe-button"><i class="fab fa-telegram-plane telegram-button"></i></button>
                </form>
            </div>
            <div class="copyright footer-bottom-text">
                {% trans "&copy;&nbsp;Copyright&nbsp;&mdash; INTERIOR 2018. All Rights Reserved." %}
            </div>
            <div class="social-block">

                <a class="social-link-f" href="#">
<i class="fab fa-facebook-f social"></i>
</a>
                <a class="social-link-f" href="#">
<i class="fab fa-twitter social"></i>
</a>
                <a class="social-link-f" href="#">
<i class="fab fa-google-plus-g social"></i>
</a>
                <a class="social-link-f" href="#">
<i class="fab fa-pinterest-p social"></i>
</a>
            </div>
            <div class="terms">
                <a class="footer-bottom-text" href="#">{% trans "Terms &amp;&nbsp;Conditions" %}</a>
                <p class="footer-bottom-text">/</p>
                <a class="footer-bottom-text" href="#">{% trans "Privacy policy &amp;&nbsp;Cookies" %}</a>
            </div>
        </footer>
    {% endblock footer%}
</div>
</body >
</html >

mainapp/templates/mainapp/contact.html
{% extends "mainapp/base.html" %}
{% load i18n %}
{% block header %}
<div class="header-content padding-site">
    {% include 'mainapp/includes/inc-header.html' with active='CONTACTS'%}
    <h2 class="header-content-h2">{% trans "Contact Us" %}</h2>
</div>
{% endblock header %}

{% block content %}
<div class="contacts-c-block padding-site">
    {% if object_list %}
        {% for contact in object_list %}
            {% include 'mainapp/includes/inc-contacts.html' with cont=contact %}
        {% endfor%}
    {% endif %}
</div>
{% endblock content %}

mainapp/templates/mainapp/index.html
{% extends "mainapp/base.html" %}
{% load static i18n %}
{% block header %}
<div class="slider padding-site">
    {% include 'mainapp/includes/inc-header.html' with active='HOME'%}
    <div class="slider-text">
        <h3>{% trans 'TRENDING' %}</h3>
        <h2>{% trans 'FISHNET CHAIR' %}</h2>
        <p>{% trans 'Seat and back with upholstery made of&nbsp;clod cure foam. Steel frame, available in&nbsp;mett powder-coated black' %}</p>
        {% include 'mainapp/includes/snippets/snip-btn-orderus.html' %}
    </div>
    {% include "mainapp/includes/snippets/snip-circle-box.html" %}
</div>
{% endblock %}
{% block content %}
<div class="featured-product padding-site">
    <div class="featured-text">
        <ul class="featured-new">
            <li><a class="active-featured-new" href="#">{% trans 'Featured' %}</a></li>
            <li><a href="#">{% trans 'New' %}</a></li>
        </ul>
        <a class="explore-all" href="#">{% trans 'explore all &gt;' %}</a>
    </div>
    {% include "mainapp/includes/inc-product-small-info.html" with products=object_list|slice:':4' div_products_cls='four-pictures-block' %}
</div>
<div class="exclusive-products">
    {% include "mainapp/includes/inc-exclusive-products.html" with products=object_list|slice:'4:6' div_products_cls='exclusive-product' %}
</div>
{% include "mainapp/includes/snippets/snip-mobile-app.html" %}
{% endblock %}

mainapp/templates/mainapp/picture_confirm_delete.html
{% extends "mainapp/base.html" %}
{% load i18n %}
{% block header %}
<div class="header-content padding-site">
    {% include 'mainapp/includes/inc-header.html' with active='PRODUCTS'%}
    <h2 class="header-content-h2">{% trans "Delete Pruduct Picture" %}</h2>
</div>
{% endblock header %}
{% block content %}

<div class="products-page-products padding-site">
<div class="product-detail-block padding-site">
    <div class="login-block-content">
        <form method="post" class="login-form form-group">
            {% csrf_token %}
            <img src="{{object.image.url}}" alt="{{object.image.title}}">
            <button type="submit" class="btn btn-primary">{% trans 'Confirm delete image' %}</button>
        </form>
    </div>
</div>
</div>
{% endblock content %}

mainapp/templates/mainapp/picture_form.html
{% extends "mainapp/base.html" %}
{% load i18n %}
{% block header %}
<div class="header-content padding-site">
    {% include 'mainapp/includes/inc-header.html' with active='PRODUCTS'%}
    <h2 class="header-content-h2">{% trans "Add new Pruduct Picture" %}</h2>
</div>
{% endblock header %}
{% block content %}

<div class="products-page-products padding-site">
<div class="product-detail-block padding-site">
    <div class="login-block-content">
        <form method="post" class="login-form form-group" enctype="multipart/form-data">
            {% csrf_token %}
            {{form.as_p}}
            <button type="submit" class="btn btn-primary">{% trans 'Save changes' %}</button>
        </form>
    </div>
</div>
</div>
{% endblock content %}

mainapp/templates/mainapp/product_detail.html
{% extends "mainapp/base.html" %}
{% load i18n %}
{% block header %}
<div class="header-content padding-site">
    {% include 'mainapp/includes/inc-header.html' with active='PRODUCTS'%}
    <h2 class="header-content-h2">{% trans "Our Products Range" %}</h2>
</div>
{% endblock header %}
{% block content %}

<div class="products-page-products padding-site">
    <div class="all-products-filter">
        {% include 'mainapp/includes/inc-categories-menu.html' with menu_cls='products-filter' objects=categories %}
    </div>
        {% if object %}
			{% include 'mainapp/includes/inc-product-detail-view.html' with product=object images=object.pictures.all price=object.prices.all.0 %}
		{% endif %}
    {% include 'mainapp/includes/inc-product-listview.html' with products=object_list div_products_cls='trending-products-imgs' %}
</div>
{% endblock content %}

mainapp/templates/mainapp/product_form.html
{% extends "mainapp/base.html" %}
{% load i18n %}
{% block header %}
<div class="header-content padding-site">
    {% include 'mainapp/includes/inc-header.html' with active='PRODUCTS'%}
    <h2 class="header-content-h2">{% trans "Add new Pruduct" %}</h2>
</div>
{% endblock header %}
{% block content %}

<div class="products-page-products padding-site">
<div class="product-detail-block padding-site">
    <div class="login-block-content">
        <form method="post" class="login-form form-group">
            {% csrf_token %}
            {{form.as_p}}
            <button type="submit" class="btn btn-primary">{% trans 'Save changes' %}</button>
        </form>
    </div>
</div>
</div>
{% endblock content %}

mainapp/templates/mainapp/product_list.html
{% extends "mainapp/base.html" %}
{% load i18n %}
{% block header %}
<div class="header-content padding-site">
    {% include 'mainapp/includes/inc-header.html' with active='PRODUCTS'%}
    <form method="post">
        {% csrf_token %}
        <input type="text" name="search" size="50" placeholder="{% trans 'Type to search' %}">
        <input type="submit" value="{% trans 'Search' %}">
    </form>
    <h2 class="header-content-h2">{% trans "Our Products Range" %}</h2>
</div>
{% endblock header %}

{% block content %}
<div class="products-page-products padding-site">
    <div class="all-products-filter">
        {% include 'mainapp/includes/inc-categories-menu.html' with menu_cls='products-filter' objects=categories %}
        
    </div>
        {% if object %}
			{% include 'mainapp/includes/inc-product-detail-view.html' with product=object %}
		{% endif %}
    {% include 'mainapp/includes/inc-product-listview.html' with products=object_list div_products_cls='trending-products-imgs' %}
</div>
{% endblock content %}

mainapp/templates/mainapp/search.html
{% extends "mainapp/base.html" %}
{% load i18n %}
{% block header %}
<div class="header-content padding-site">
    {% include 'mainapp/includes/inc-header.html' with active='PRODUCTS'%}
    <form method="post" action="{% url 'mainapp:search' %}">
        {% csrf_token %}
        <input type="text" name="search" size="50" placeholder="{% trans 'Type to search' %}">
        <input type="submit" value="{% trans 'Search' %}">
    </form>
    <h2 class="header-content-h2">{% trans "Search results" %}</h2>
</div>
{% endblock header %}

{% block content %}
<div class="products-page-products padding-site">
    <div class="all-products-filter">
        {% include 'mainapp/includes/inc-categories-menu.html' with menu_cls='products-filter' objects=categories %}

    </div>
    {% if object %}
    {% include 'mainapp/includes/inc-product-detail-view.html' with product=object %}
    {% endif %}
    {% include 'mainapp/includes/inc-product-listview.html' with products=object_list div_products_cls='trending-products-imgs' %}
</div>
{% endblock content %}